### ISSUE TITLE
Link checker for all documentation pages

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/NMDC_documentation#9] opened 2022-06-03 18:53 UTC
Per @cmungall recommendation, would be good to implement a URL checking for all documentation pages to make sure that there aren't any broken links. 

FYI @turbomam

**Comment by ssarrafan** [comment] 2022-06-03 19:00
Adding for July. Need to figure out who to assign.

**Comment by ssarrafan** [comment] 2022-07-08 19:01
Sent to a note to Chris, Mark, Sujay and Patrick to see who we can work on this.

**Comment by ssarrafan** [comment] 2022-07-08 19:10
Patrick volunteered to look at this issue. Assigned to Patrick now.

**Comment by pkalita-lbl** [comment] 2022-07-14 19:07
@pvangay @kwdavenport @yxu-lanl @hubin-keio @turbomam 

I set up link checking as a GitHub Action on my fork of this repo. Here's an example of the output it produces:

https://github.com/pkalita-lbl/NMDC_documentation/actions/runs/2672391297

A few notes:

1. Failures where the URL starts with `file://` indicate that the source Markdown file is attempting to refer to another _local_ file that does not exist.
2. You might see some failures for GitHub ULRs (i.e. `https://github.com/microbiomedata/nmdc-metadata/pull/297`) and click on the link and think "that link works just fine". But those often are links to repositories with some kind of access control. If you were to open that link in an incognito window you would get a 404 page.
3. If you're wondering about the 1012 Excluded links in the summary, that is because nearly every page in `docs/reference/metadata` has a link to `https://microbiomedata/meta/...` (for example, on [this page](https://nmdc-documentation.readthedocs.io/en/latest/reference/metadata/NamedThing.html) it's the link with the text "nmdc:NamedThing"). This is something that should be worked out in the schema, but in the meantime seeing those 1000+ bad links adds too much noise to the report. So I [filtered them out](https://github.com/pkalita-lbl/NMDC_documentation/blob/dc2b107f17ec2a3c84f1d3e5bb06f96475f609b1/lychee.toml#L5).

So at this point I'd welcome your feedback, especially on:

1. Does this report format seem useful and actionable as is? There is also a possibility of automatically generating GitHub Issues for each failure. That's something we could consider setting up now or in the future. 
2. Currently in my fork the link checking workflow is set to only run when manually triggered. I assume we'd actually want this to run on pull requests or pushes to `main` and possibly also on a periodic schedule to catch links that may go bad as external sites change over time. Maybe a weekly or monthly schedule for that?

**Comment by hubin-keio** [comment] 2022-07-15 00:40
Thanks, @pkalita-lbl. It would be great if the link checking is triggered automatically by code submission/commits. I also like the example output you shared. I am not sure about automate issue creation. If a new code submitted find failed links (, which may not necessarily be caused by the new code), perhaps we can just let that code stay in a feature branch (no merging allowed) and notify the submitter and the package maintainer?

**Comment by pkalita-lbl** [comment] 2022-07-15 16:50
Thanks for the feedback @hubin-keio! I've updated my fork so that the workflow is triggered by pull requests to `main` ([for example](https://github.com/pkalita-lbl/NMDC_documentation/pull/1)) or direct commits to `main` (just in case a PR isn't used). In either case an email notification will be sent to the original committer if the workflow fails (i.e. it finds broken links). 

I agree that automatic issue creation is probably overkill at this point. I just wanted to make sure people knew that was an option. 

One other thing I should have mentioned before is that it's not hard to run the same check locally before committing. I can add information about that to the README.

**Comment by hubin-keio** [comment] 2022-07-15 17:31
Yes, some instructions on how to check it locally before commit will be great! Thanks, @pkalita-lbl !

**Comment by pkalita-lbl** [comment] 2022-07-15 23:05
I've opened a pull request here: https://github.com/microbiomedata/NMDC_documentation/pull/13 but please feel free to continue to provide feedback here or on the PR!

**Closed** 2022-07-27 20:16 UTC
